spring.application.name=spring-graphql
# ===============================
# CONFIGURATION POSTGRESQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_graphql
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURATION GRAPHQL
# ===============================

spring.graphql.graphiql.enabled=true


